chore(husky): enhance pre-push hook to build documentation and validate before pushing

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -9,6 +9,15 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+echo "Building docus..."
+pnpm docs:build
+
+if [ $? -ne 0 ]; then
+  echo "❌ Build docs failed. Push aborted."
+  echo "Fix the build errors before pushing."
+  exit 1
+fi
+
 echo "Running tests..."
 pnpm test
 
